### ISSUE TITLE
Some minor suggestions

### ISSUE THREAD

**Issue by eduardo-rodrigues** [jpivarski/pyhep2020-poster#2]
* [x] I would suggest that we put the URL to the PyHEP workshop somewhere on the top-right of the page. To be seen once the rest of the text gets fixed.
   * [x] We could say "3rd workshop on Python..." instead of just "Workshop on Python...". It's true, many do this counting (e.g. CHEP), and it shows that we're talking about a workshop series.
   * [x] I'm not sure about the SciPy logo, especially if we have none for PyHEP itself. It catches the eye and is hence misleading.
   * [x] The HSF and UT logos seem a bit too large.

**Comment by jpivarski** [comment]
Thanks! I'll keep those in mind when I start to work on the graphical design. (I haven't yet—this is just a copy-paste dump of logos, not meant to represent what it will look like.)

**Comment by eduardo-rodrigues** [comment]
I forgot to say 2 obvious things:
- Great and speedy work already!
- Other opinions are welcome on the above.

**Comment by jpivarski** [comment]
I took all of your suggestions into account, so I made few different decisions in the end.
