### ISSUE TITLE
Use non-Times New Roman font

### ISSUE THREAD

**Issue by ponyisi** [jpivarski/pyhep2020-poster#5]
Suggestion: replace the serif with a non-Times typeface (looks too generic otherwise ...)

**Comment by jpivarski** [comment]
It was actually Bookman... I was trying a few fonts, not expecting to like a serif one. But I can keep looking.

I don't install fonts on my computer (I'd just forget to reinstall them on the next), but I could search the Google font registry. Maybe they'd let me download an SVG path of the text, without having to install the font itself...

**Comment by ponyisi** [comment]
Ah, I see, it's just that I don't have URW Bookman installed on my machine.  Carry on ... :-)  (Though a PDF version would be more interoperable)

**Comment by jpivarski** [comment]
Since the text is not going to change, I could replace it with an SVG path.
